[package]
name = "ekf"
version = "0.1.0"
edition = "2024"

[dependencies]
robotic_algorithms = { path = "../../" }
rand = "0.8"
rand_distr = "0.4"
nalgebra = "0.33.2"
eframe = "0.31.1"
egui = "0.31.1"
egui_plot = "0.32.1"